### ISSUE TITLE
tuple index out of range error

### ISSUE THREAD

**Issue by mja** [PharmGKB/PGxPOP#13]
When running the command

```sh
python PGxPOP/bin/PGxPOP.py --vcf chr10_HRC.vcf.gz --gene CYP2C19 --phased --build hg19 --batch --output cyp2c19 
```

I'm getting the error

```sh
Traceback (most recent call last):
  File "PGxPOP/bin/PGxPOP.py", line 308, in <module>
    cd.run()
  File "PGxPOP/bin/PGxPOP.py", line 54, in run
    results = self.process_gene(g)
  File "PGxPOP/bin/PGxPOP.py", line 68, in process_gene
    diplotypes, sample_variants, uncallable = self.get_calls(gene, gt_matrices)
  File "PGxPOP/bin/PGxPOP.py", line 177, in get_calls
    for samp in range(gt_mat[0].shape[1]):
IndexError: tuple index out of range
```

Here is a [gist with the `--debug` output](https://gist.github.com/mja/b2493a2c4be8efb0f91864a6190fd6a4). 

Is it possibly because not all of the variants are in the VCF file?

**Comment by mja** [comment]
OK, I think I've gotten it to run by not  using the `--batch` argument.
